# Generated by Django 5.2.5 on 2025-09-12 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('class_letter', models.CharField(max_length=1)),
                ('primary_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('interim_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('final_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnostic.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnostic.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
