# Generated by Django 4.2.4 on 2025-09-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='letter',
        ),
    ]
