# Generated by Django 5.2.5 on 2025-08-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_classletter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_letter', models.CharField(max_length=1)),
                ('primary_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('interim_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('final_diagnosis_score', models.FloatField(blank=True, null=True)),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.classlevel')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassLetter',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
