# Generated by Django 5.2.5 on 2025-09-12 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('test_type', models.CharField(choices=[('primary', 'Первичная диагностика'), ('interim', 'Промежуточная диагностика'), ('final', 'Итоговая диагностика')], max_length=50)),
                ('block', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='primary_test.block')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(null=True)),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='primary_test.answeroption')),
                ('diagnostic_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='primary_test.diagnosticresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primary_test.question')),
            ],
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='primary_test.question'),
        ),
    ]
