# Generated by Django 5.2.5 on 2025-09-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='linked_questions', to='primary_test.answeroption'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='primary_test.question'),
        ),
    ]
