# Generated by Django 4.2.4 on 2025-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='linked_questions', to='primary_test.answeroption'),
        ),
    ]
