# Generated by Django 4.2.4 on 2025-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary_test', '0002_question_options_alter_answeroption_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
